### ISSUE TITLE
Ask for Help to Install Geniatech HDStar SU3000

### ISSUE THREAD

**Issue by picatchoof** [redblue-pkt/su3000-geniatech-hdstar-v3#1]
Hello all,
please need your help to get the USB Box Geniatech HDStar works properly.
the situation in my Installation looks like:

**pi@raspberrypi:~ $ uname -a**
Linux raspberrypi 5.10.43v64 #1 SMP PREEMPT Tue Jun 15 00:52:48 CEST 2021 aarch64 GNU/Linux

pi@raspberrypi:~ $ dmesg | grep dvb
[    3.697288] udevd[155]: Error running install command for dvb_core
[    8.147607] dvb-usb: found a 'SU3000HD DVB-S USB2.0' in warm state.
[    8.156793] dvb-usb: will pass the complete MPEG2 transport stream to the software demuxer.
[    8.157383] dvbdev: DVB: registering new adapter (SU3000HD DVB-S USB2.0)
[    8.163040] dvb-usb: MAC address: 00:af:78:66:2f:70
[    8.165704] dvbdev: dvb_create_media_entity: media entity 'dvb-demux' registered.
[    8.498844] dvb-usb: no frontend was attached by 'SU3000HD DVB-S USB2.0'
[    8.500312] dvb-usb: schedule remote query interval to 150 msecs.
**[    8.500326] dvb-usb: SU3000HD DVB-S USB2.0 successfully initialized and connected.**

**pi@raspberrypi:~ $ ls -R /dev/dvb**
/dev/dvb:
adapter0

/dev/dvb/adapter0:
demux0  dvr0  net0

**pi@raspberrypi:~ $ tslsdvb** 
tslsdvb: **no DVB device found**

**pi@raspberrypi:~ $ sudo dvblast -f 12467000 -s 41667000 -v 18**
DVBlast 3.4 (release)
warning: restarting
debug: compiled with DVB API version 5.11
error: opening device /dev/dvb/adapter0/frontend0 **failed (No such file or directory)**

I can not figure out how to make the Device Recognized by the DVB Tools I'm used to. like TSDuck (tslsdvb) DVBLast

**Comment by redblue-pkt** [comment]
Exactly what version of the hardware do you have? HdStar Geniatech v3?

**Comment by picatchoof** [comment]
Hello Sir,
Yes in fact the box is SU3000 V3 Chip Montage M88TS2022

**Comment by redblue-pkt** [comment]
Try to download my repo and compile now. Everything should work. I made a few corrections yesterday and it works for me. My device has the M88TS2022 and M88DS3103B.

**Comment by picatchoof** [comment]
hello Sir
Thanx a lot 
Forgive me I'm new in Linux but it seems that I had Kernel issues
when I do 
make command I get this 

**~/su3000-geniatech-hdstar-v3 $ make
make -C /lib/modules/5.15.56-v7l+/build M=/home/smartbeam/su3000-geniatech-hdstar-v3 modules
make[1]: *** /lib/modules/5.15.56-v7l+/build: No such file or directory.  Stop.
make: *** [Makefile:12: all] Error 2**

can suggest any job that must be done from my side?
Best Regards

**Comment by redblue-pkt** [comment]
You need to install linux headers.

**Comment by picatchoof** [comment]
Hello Dear 
Thanx a lot for your help
I did somthing worong
I run a wrong command that tells remove old driver (maybe rmmob)
now it's worst even the DMESG gives nothing and even the /dev does not have the DVB folder

**dmesg | grep **3000****
[    0.000000]   HighMem  [mem 0x0000000030000000-0x00000001ffffffff]
[    1.655409] mmc-bcm2835 fe300000.mmcnr: mmc_debug:0 mmc_debug2:0
[    1.655430] mmc-bcm2835 fe300000.mmcnr: DMA channel allocated
[    3.125154] usb 1-1.4: New USB device found, idVendor=1f4d, idProduct=3000, bcdDevice= 0.00
[    7.300059] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43455-sdio.raspberrypi,4-model-b.bin failed with error -2

**smartbeam@smartbeam:~ $ dmesg | grep dvb**
Grep dvb gives nothing
and lsusb gives:
**smartbeam@smartbeam:~ $ lsusb**
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
**Bus 001 Device 005: ID 1f4d:3000 G-Tek Electronics Group USB Stick**
Bus 001 Device 004: ID 046d:c018 Logitech, Inc. Optical Wheel Mouse
Bus 001 Device 003: ID 03f0:0024 HP, Inc KU-0316 Keyboard
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
smartbeam@smartbeam:~ $ 

I tried drivers from TBS and others but no Result
thanx a lot

**Comment by redblue-pkt** [comment]
You need to install linux headers first. If you are using armbian, this is what armbian-config is for. You choose linux-headers installations from the menu. The dvb folder in / dev is created only after loading the driver from the tv tuner. The TBS drivers are not for your hardware.

**Comment by picatchoof** [comment]
Hello again
I did new Installation from scratch Raspian 32bit (The recommanded one)
I Install the headers:
**sudo apt install raspberrypi-kernel-headers** 
after I get to your folder and run 
sudo make
sudo make install
I don't know if this is the way to recompile your Sources Files.

In the folder /lib/firmware ther is **no dvb-fe-ds3000.fw** 

the DMESG is somehow showing the DVB Device But the DVBLAST command shows error (No file).:

**smartbeam@smartbeam:~ $ dmesg | grep dvb**
[   10.131643] dvb-usb: found a 'SU3000HD DVB-S USB2.0' in warm state.
[   10.177838] dvb-usb: will pass the complete MPEG2 transport stream to the software demuxer.
[   10.186466] dvbdev: DVB: registering new adapter (SU3000HD DVB-S USB2.0)
[   10.191252] dvb-usb: MAC address: 00:af:78:66:2f:70
[   10.192282] dvbdev: dvb_create_media_entity: media entity 'dvb-demux' registered.
[   10.654085] dvb-usb: no frontend was attached by 'SU3000HD DVB-S USB2.0'
[   10.656022] dvb-usb: schedule remote query interval to 150 msecs.
_**[   10.656038] dvb-usb: SU3000HD DVB-S USB2.0 successfully initialized and connected.**_

**smartbeam@smartbeam:~ $ dvblast -f 12476000 -s 41467000 -v 18**
DVBlast 3.4 (release)
warning: restarting
debug: compiled with DVB API version 5.11
**error: opening device /dev/dvb/adapter0/frontend0 failed (No such file or directory)**

**smartbeam@smartbeam:~ $ ls -l /dev/dvb/**
total 0
drwxr-xr-x 2 root root 100 Aug 19 17:51 **adapter0**
smartbeam@smartbeam:~ $ 

at this level there is no **frontend0** folder created after all those actions

BTW if you have time I can give you remote acces (remote SSH) to check.
smartbeam.ddns.net:8022

Appreciate your involvement and help
best regards

**Comment by redblue-pkt** [comment]
Provide the full dmeasg log. I made a fix on the last day, did you download the update? HdStar V3 uses a different firmware, dvb-demod-m88ds3103b.fw. Download my repo again and compile it. My repo also has up-to-date firmware.

**Comment by picatchoof** [comment]
Hello
Really sorry to bather you
I spent more than 8 hrs yesterday, and almost 10 hts today.
I did reflash the RPi more that 6 Times.
I copied all *.fw files from your folder in /lib/firmware
reboot
and no result

you can connect via SSH
url: ****************
port: *********
user: **********
pwd: *************

the complete DMESG is attached:

[dmesg.txt](https://github.com/redblue-pkt/su3000-geniatech-hdstar-v3/files/9384718/dmesg.txt)

Appreciate

BTW TSDuck is installed you can check the device using the command: **tslsdvb**

**Comment by picatchoof** [comment]
Hello.
Attached two images that shows the Montage chips
**TS2022
M88DS3203B**


![IMG_20220819_223922.jpg](https://user-images.githubusercontent.com/21952865/185710816-5dd64856-32f3-41be-bd45-6673f64e14e2.jpg)

![IMG_20220819_223830.jpg](https://user-images.githubusercontent.com/21952865/185710837-eabe9209-09ce-40f4-8d5e-bee9d36d371e.jpg)

**Comment by redblue-pkt** [comment]
Same hardware as mine. The problem is on the RPI side. Somehow it loads old kernel modules all the time. Don't you have some other linux device?

**Comment by picatchoof** [comment]
I can change this ROM and flash an other distro.
Like debian or Ubuntu.

**Comment by redblue-pkt** [comment]
Ubuntu.

**Comment by picatchoof** [comment]
Ok i will try to prepare an new SD Card within Ubuntu server 20.04

**Comment by redblue-pkt** [comment]
Let me know when you're done.

**Comment by picatchoof** [comment]
Hello again
Sorry making you waiting for me.

The Ubuntu Server is ready.
Same url/port
User: ********
Pwd: ********

Thnx

**Comment by redblue-pkt** [comment]
What do you want to use the now working tuner for? Tvheadend?

**Comment by picatchoof** [comment]
Hello bro.
I really like to thank you soooo much

You are the best 
Appreciate.

I will try to record a Sample stream from Eutelsat E7W and work with that stream for other purposes.
With my little experience I did it before using Tsduck
But i know it can be done by the otherd linuxdvb binaries.
Or dvbsnoop

Freq 12476
SR 41467 Msbpr
Pol: H 
Mod: DVB-S2 8 PSK

**Comment by redblue-pkt** [comment]
Have fun, I'm glad that I helped.
